import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
import Button from "../../components/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const { push } = router;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="buttonContainer">
          <Button destination={"Farm"} push={push} text={"Farm"} />
          <Button destination={"Market"} push={push} text={"Market"} />
          <Button
            destination={"Weather"}
            push={push}
            text={"Weather Forecast"}
          />
          <Button destination={"Rankings"} push={push} text={"Rankings"} />
        </section>
      </main>
    </>
  );
}
